export const challenges = [
  {
    id: 1,
    title: 'Caesar\'s Secret',
    difficulty: 'Easy',
    points: 100,
    category: 'Classical',
    description: 'A message was intercepted from an ancient Roman commander. Decode it.',
    ciphertext: 'Wkh vhfuhw frgh lv: YLFWRUB',
    hint: 'Try shifting each letter back by a small number...',
    solution: 'The secret code is: VICTORY',
    method: 'Caesar Cipher with shift 3',
  },
  {
    id: 2,
    title: 'Base Layers',
    difficulty: 'Easy',
    points: 100,
    category: 'Encoding',
    description: 'This message has been encoded twice. Peel back the layers.',
    ciphertext: 'NFVTQTZTMU2DQNBZHE4TSMJQ',
    hint: 'Think about Base32 first, then another common encoding...',
    solution: 'crypto_master',
    method: 'Base32 → Base64 decode',
  },
  {
    id: 3,
    title: 'XOR Challenge',
    difficulty: 'Medium',
    points: 200,
    category: 'Classical',
    description: 'This hex string was XORed with a single character key. Find the message.',
    ciphertext: '2b 26 20 3a 38 71 29 26 71 2e 20 71 13 5e 12',
    hint: 'Try XORing with each ASCII character and look for readable English...',
    solution: 'HELLO_MY_NAME',
    method: 'XOR with key byte',
  },
  {
    id: 4,
    title: 'Vigenère Vault',
    difficulty: 'Medium',
    points: 250,
    category: 'Classical',
    description: 'The Kasiski test reveals a key length of 3. Crack this Vigenère cipher.',
    ciphertext: 'LXFOPVEFRNHR',
    hint: 'Key length is 3. Use frequency analysis on every 3rd letter...',
    solution: 'ATTACKATDAWN',
    method: 'Vigenère with key "KEY"',
  },
  {
    id: 5,
    title: 'Hash Detective',
    difficulty: 'Easy',
    points: 150,
    category: 'Hashing',
    description: 'Identify what type of hash this is: 5d41402abc4b2a76b9719d911017c592',
    ciphertext: '5d41402abc4b2a76b9719d911017c592',
    hint: 'Count the characters. Different hash algorithms produce different lengths.',
    solution: 'MD5 hash of "hello"',
    method: 'Hash length = 32 hex chars = 128 bits = MD5',
  },
  {
    id: 6,
    title: 'Rail Fence Runner',
    difficulty: 'Medium',
    points: 200,
    category: 'Classical',
    description: 'This message was written in a zigzag pattern. Decode it.',
    ciphertext: 'Hloel llWrd',
    hint: 'Try different numbers of rails (2, 3, 4...).',
    solution: 'Hello World',
    method: 'Rail Fence with 2 rails',
  },
  {
    id: 7,
    title: 'Morse Mayhem',
    difficulty: 'Easy',
    points: 100,
    category: 'Encoding',
    description: 'Decode this Morse code transmission.',
    ciphertext: '.... . .-.. .-.. --- / .-- --- .-. .-.. -.. ',
    hint: 'Dots and dashes... a very old telegraph encoding.',
    solution: 'HELLO WORLD',
    method: 'Morse Code decode',
  },
  {
    id: 8,
    title: 'Multi-Layer Madness',
    difficulty: 'Hard',
    points: 400,
    category: 'Mixed',
    description: 'This message was encoded with multiple layers. Reverse all of them.',
    ciphertext: 'Vm0wd2QyUXlVWGw=',
    hint: 'Start with Base64. Then look at what you get...',
    solution: 'Decoded multi-layer',
    method: 'Base64 → Hex → ASCII',
  },
  {
    id: 9,
    title: 'Affine Assault',
    difficulty: 'Hard',
    points: 350,
    category: 'Classical',
    description: 'An affine cipher with a=7, b=2. Decrypt: IHHWJR',
    ciphertext: 'IHHWJR',
    hint: 'You need the modular inverse of 7 mod 26.',
    solution: 'CRYPTO',
    method: 'Affine cipher with a=7, b=2',
  },
  {
    id: 10,
    title: 'Bacon\'s Hidden Message',
    difficulty: 'Medium',
    points: 250,
    category: 'Classical',
    description: 'Decode this Bacon cipher: AABBB AABAA ABABB ABABB ABBBA',
    ciphertext: 'AABBB AABAA ABABB ABABB ABBBA',
    hint: 'Each group of 5 A/B characters represents one letter.',
    solution: 'HELLO',
    method: "Bacon's Cipher decode",
  },
];

export function getDifficultyColor(difficulty) {
  switch (difficulty) {
    case 'Easy': return 'text-green-400 bg-green-400/10 border-green-400/20';
    case 'Medium': return 'text-yellow-400 bg-yellow-400/10 border-yellow-400/20';
    case 'Hard': return 'text-red-400 bg-red-400/10 border-red-400/20';
    default: return 'text-muted-foreground';
  }
}