import {
  rot13, rot47, caesarEncrypt, caesarDecrypt, caesarBruteForce,
  vigenereEncrypt, vigenereDecrypt, affineEncrypt, affineDecrypt,
  railFenceEncrypt, railFenceDecrypt, xorEncrypt, xorToHex,
  baconEncrypt, baconDecrypt, polybiusEncrypt, polybiusDecrypt,
  columnarEncrypt, columnarDecrypt, beaufortEncrypt, beaufortDecrypt,
  autokeyEncrypt, autokeyDecrypt, atbash,
  playfairEncrypt, playfairDecrypt,
  foursquareEncrypt, foursquareDecrypt,
  runningKeyEncrypt, runningKeyDecrypt,
  gronsfeldEncrypt, gronsfeldDecrypt,
  adfgxEncrypt, adfgxDecrypt,
  nihilistEncrypt, nihilistDecrypt,
  portaEncrypt, portaDecrypt,
  twosquareEncrypt, twosquareDecrypt
} from './classical';

import {
  base64Encode, base64Decode, hexEncode, hexDecode,
  binaryEncode, binaryDecode, octalEncode, octalDecode,
  decimalEncode, decimalDecode, urlEncode, urlDecode,
  htmlEncode, htmlDecode, unicodeEscape, unicodeUnescape,
  morseEncode, morseDecode, base32Encode, base32Decode,
  base58Encode, base58Decode, reverseText,
  base45Encode, base45Decode, base62Encode, base62Decode,
  base85Encode, base85Decode, base92Encode, base92Decode,
  toBraille, fromBraille, toCharcode, fromCharcode
} from './encodings';

// Registry of all cipher operations - sorted alphabetically by name
export const cipherRegistry = {
  adfgx: {
    name: 'ADFGX Cipher',
    category: 'classical',
    description: 'Fractionating cipher using ADFGX letters',
    params: [{ name: 'key', type: 'text', default: 'KEY', label: 'Transposition Key' }],
    encode: (text, { key }) => adfgxEncrypt(text, key),
    decode: (text, { key }) => adfgxDecrypt(text, key),
    reversible: true,
  },
  affine: {
    name: 'Affine Cipher',
    category: 'classical',
    description: 'Uses mathematical function (ax + b) mod 26',
    params: [
      { name: 'a', type: 'number', default: 5, label: 'a (coprime to 26)' },
      { name: 'b', type: 'number', default: 8, label: 'b' },
    ],
    encode: (text, { a = 5, b = 8 }) => affineEncrypt(text, a, b),
    decode: (text, { a = 5, b = 8 }) => affineDecrypt(text, a, b),
    reversible: true,
  },
  atbash: {
    name: 'Atbash Cipher',
    category: 'classical',
    description: 'Reverses the alphabet (A↔Z, B↔Y, etc.)',
    params: [],
    encode: (text) => atbash(text),
    decode: (text) => atbash(text),
    reversible: true,
  },
  autokey: {
    name: 'Autokey Cipher',
    category: 'classical',
    description: 'Vigenère variant using plaintext as part of the key',
    params: [{ name: 'key', type: 'text', default: 'KEY', label: 'Key' }],
    encode: (text, { key }) => autokeyEncrypt(text, key),
    decode: (text, { key }) => autokeyDecrypt(text, key),
    reversible: true,
  },
  bacon: {
    name: "Bacon's Cipher",
    category: 'classical',
    description: 'Encodes letters as 5-bit binary using A and B',
    params: [],
    encode: (text) => baconEncrypt(text),
    decode: (text) => baconDecrypt(text),
    reversible: true,
  },
  base32: {
    name: 'Base32',
    category: 'encoding',
    description: 'Base32 encoding (RFC 4648)',
    params: [],
    encode: (text) => base32Encode(text),
    decode: (text) => base32Decode(text),
    reversible: true,
  },
  base45: {
    name: 'Base45',
    category: 'encoding',
    description: 'Compact base45 encoding (used in QR codes)',
    params: [],
    encode: (text) => base45Encode(text),
    decode: (text) => base45Decode(text),
    reversible: true,
  },
  base58: {
    name: 'Base58',
    category: 'encoding',
    description: 'Base58 encoding (Bitcoin-style)',
    params: [],
    encode: (text) => base58Encode(text),
    decode: (text) => base58Decode(text),
    reversible: true,
  },
  base62: {
    name: 'Base62',
    category: 'encoding',
    description: 'Base62 encoding (URL-safe, no padding)',
    params: [],
    encode: (text) => base62Encode(text),
    decode: (text) => base62Decode(text),
    reversible: true,
  },
  base64: {
    name: 'Base64',
    category: 'encoding',
    description: 'Standard Base64 encoding',
    params: [],
    encode: (text) => base64Encode(text),
    decode: (text) => base64Decode(text),
    reversible: true,
  },
  base85: {
    name: 'Base85 (Ascii85)',
    category: 'encoding',
    description: 'Ascii85 encoding (used in PDF/PostScript)',
    params: [],
    encode: (text) => base85Encode(text),
    decode: (text) => base85Decode(text),
    reversible: true,
  },
  base92: {
    name: 'Base92',
    category: 'encoding',
    description: 'Very compact base92 encoding',
    params: [],
    encode: (text) => base92Encode(text),
    decode: (text) => base92Decode(text),
    reversible: true,
  },
  beaufort: {
    name: 'Beaufort Cipher',
    category: 'classical',
    description: 'Vigenère variant where encryption = decryption',
    params: [{ name: 'key', type: 'text', default: 'KEY', label: 'Key' }],
    encode: (text, { key }) => beaufortEncrypt(text, key),
    decode: (text, { key }) => beaufortDecrypt(text, key),
    reversible: true,
  },
  binary: {
    name: 'Binary',
    category: 'encoding',
    description: 'Converts to/from 8-bit binary strings',
    params: [],
    encode: (text) => binaryEncode(text),
    decode: (text) => binaryDecode(text),
    reversible: true,
  },
  braille: {
    name: 'Braille',
    category: 'encoding',
    description: 'Convert text to Unicode Braille patterns',
    params: [],
    encode: (text) => toBraille(text),
    decode: (text) => fromBraille(text),
    reversible: true,
  },
  caesar: {
    name: 'Caesar Cipher',
    category: 'classical',
    description: 'Shifts each letter by a fixed number of positions',
    params: [{ name: 'shift', type: 'number', default: 3, min: 0, max: 25, label: 'Shift' }],
    encode: (text, { shift = 3 }) => caesarEncrypt(text, shift),
    decode: (text, { shift = 3 }) => caesarDecrypt(text, shift),
    bruteForce: (text) => caesarBruteForce(text),
    reversible: true,
  },
  charcode: {
    name: 'Charcode',
    category: 'encoding',
    description: 'Convert to/from character codes',
    params: [],
    encode: (text) => toCharcode(text),
    decode: (text) => fromCharcode(text),
    reversible: true,
  },
  columnar: {
    name: 'Columnar Transposition',
    category: 'classical',
    description: 'Rearranges text using a keyword column order',
    params: [{ name: 'key', type: 'text', default: 'CIPHER', label: 'Key' }],
    encode: (text, { key }) => columnarEncrypt(text, key),
    decode: (text, { key }) => columnarDecrypt(text, key),
    reversible: true,
  },
  decimal: {
    name: 'Decimal ASCII',
    category: 'encoding',
    description: 'Converts to/from decimal character codes',
    params: [],
    encode: (text) => decimalEncode(text),
    decode: (text) => decimalDecode(text),
    reversible: true,
  },
  foursquare: {
    name: 'Four-Square Cipher',
    category: 'classical',
    description: 'Uses four 5×5 matrices for encryption',
    params: [
      { name: 'key1', type: 'text', default: 'KEY1', label: 'Key 1' },
      { name: 'key2', type: 'text', default: 'KEY2', label: 'Key 2' },
    ],
    encode: (text, { key1, key2 }) => foursquareEncrypt(text, key1, key2),
    decode: (text, { key1, key2 }) => foursquareDecrypt(text, key1, key2),
    reversible: true,
  },
  gronsfeld: {
    name: 'Gronsfeld Cipher',
    category: 'classical',
    description: 'Vigenère variant using numeric key',
    params: [{ name: 'key', type: 'text', default: '12345', label: 'Numeric Key' }],
    encode: (text, { key }) => gronsfeldEncrypt(text, key),
    decode: (text, { key }) => gronsfeldDecrypt(text, key),
    reversible: true,
  },
  hex: {
    name: 'Hexadecimal',
    category: 'encoding',
    description: 'Converts to/from hex representation',
    params: [],
    encode: (text) => hexEncode(text),
    decode: (text) => hexDecode(text),
    reversible: true,
  },
  html: {
    name: 'HTML Entities',
    category: 'encoding',
    description: 'HTML entity encoding',
    params: [],
    encode: (text) => htmlEncode(text),
    decode: (text) => htmlDecode(text),
    reversible: true,
  },
  morse: {
    name: 'Morse Code',
    category: 'encoding',
    description: 'Encodes text as Morse code dots and dashes',
    params: [],
    encode: (text) => morseEncode(text),
    decode: (text) => morseDecode(text),
    reversible: true,
  },
  nihilist: {
    name: 'Nihilist Cipher',
    category: 'classical',
    description: 'Polybius-based cipher with numeric key',
    params: [
      { name: 'keyword', type: 'text', default: 'KEYWORD', label: 'Keyword' },
      { name: 'keyNumbers', type: 'text', default: '53', label: 'Key Numbers' },
    ],
    encode: (text, { keyword, keyNumbers }) => nihilistEncrypt(text, keyword, keyNumbers),
    decode: (text, { keyword, keyNumbers }) => nihilistDecrypt(text, keyword, keyNumbers),
    reversible: true,
  },
  octal: {
    name: 'Octal',
    category: 'encoding',
    description: 'Converts to/from octal representation',
    params: [],
    encode: (text) => octalEncode(text),
    decode: (text) => octalDecode(text),
    reversible: true,
  },
  playfair: {
    name: 'Playfair Cipher',
    category: 'classical',
    description: 'Encrypts letter pairs using 5×5 matrix',
    params: [{ name: 'key', type: 'text', default: 'KEYWORD', label: 'Key' }],
    encode: (text, { key }) => playfairEncrypt(text, key),
    decode: (text, { key }) => playfairDecrypt(text, key),
    reversible: true,
  },
  polybius: {
    name: 'Polybius Square',
    category: 'classical',
    description: 'Encodes letters as coordinate pairs in a 5×5 grid',
    params: [],
    encode: (text) => polybiusEncrypt(text),
    decode: (text) => polybiusDecrypt(text),
    reversible: true,
  },
  porta: {
    name: 'Porta Cipher',
    category: 'classical',
    description: 'Reciprocal cipher using 13 alphabet pairs',
    params: [{ name: 'key', type: 'text', default: 'KEY', label: 'Key' }],
    encode: (text, { key }) => portaEncrypt(text, key),
    decode: (text, { key }) => portaDecrypt(text, key),
    reversible: true,
  },
  railfence: {
    name: 'Rail Fence Cipher',
    category: 'classical',
    description: 'Writes text in zigzag pattern across rails',
    params: [{ name: 'rails', type: 'number', default: 3, min: 2, max: 20, label: 'Rails' }],
    encode: (text, { rails = 3 }) => railFenceEncrypt(text, rails),
    decode: (text, { rails = 3 }) => railFenceDecrypt(text, rails),
    reversible: true,
  },
  reverse: {
    name: 'Reverse',
    category: 'encoding',
    description: 'Reverses the string',
    params: [],
    encode: (text) => reverseText(text),
    decode: (text) => reverseText(text),
    reversible: true,
  },
  rot13: {
    name: 'ROT13',
    category: 'classical',
    description: 'Rotates each letter 13 positions in the alphabet',
    params: [],
    encode: (text) => rot13(text),
    decode: (text) => rot13(text),
    reversible: true,
  },
  rot47: {
    name: 'ROT47',
    category: 'classical',
    description: 'Rotates ASCII characters 47 positions',
    params: [],
    encode: (text) => rot47(text),
    decode: (text) => rot47(text),
    reversible: true,
  },
  runningkey: {
    name: 'Running Key Cipher',
    category: 'classical',
    description: 'Vigenère variant using book text as key',
    params: [{ name: 'key', type: 'text', default: 'SECRETKEY', label: 'Key' }],
    encode: (text, { key }) => runningKeyEncrypt(text, key),
    decode: (text, { key }) => runningKeyDecrypt(text, key),
    reversible: true,
  },
  twosquare: {
    name: 'Two-Square Cipher',
    category: 'classical',
    description: 'Digraph cipher using two 5×5 matrices',
    params: [
      { name: 'key1', type: 'text', default: 'KEY1', label: 'Key 1' },
      { name: 'key2', type: 'text', default: 'KEY2', label: 'Key 2' },
    ],
    encode: (text, { key1, key2 }) => twosquareEncrypt(text, key1, key2),
    decode: (text, { key1, key2 }) => twosquareDecrypt(text, key1, key2),
    reversible: true,
  },
  unicode: {
    name: 'Unicode Escape',
    category: 'encoding',
    description: 'Unicode \\uXXXX escape sequences',
    params: [],
    encode: (text) => unicodeEscape(text),
    decode: (text) => unicodeUnescape(text),
    reversible: true,
  },
  url: {
    name: 'URL Encoding',
    category: 'encoding',
    description: 'Percent-encoding for URLs',
    params: [],
    encode: (text) => urlEncode(text),
    decode: (text) => urlDecode(text),
    reversible: true,
  },
  vigenere: {
    name: 'Vigenère Cipher',
    category: 'classical',
    description: 'Polyalphabetic substitution using a keyword',
    params: [{ name: 'key', type: 'text', default: 'KEY', label: 'Key' }],
    encode: (text, { key }) => vigenereEncrypt(text, key),
    decode: (text, { key }) => vigenereDecrypt(text, key),
    reversible: true,
  },
  xor: {
    name: 'XOR Cipher',
    category: 'classical',
    description: 'XOR each byte with a key',
    params: [{ name: 'key', type: 'text', default: 'K', label: 'Key' }],
    encode: (text, { key }) => xorToHex(text, key),
    decode: (text, { key }) => xorEncrypt(text, key),
    reversible: true,
  },
};

export const categories = {
  classical: { name: 'Classical Ciphers', icon: 'Shield' },
  encoding: { name: 'Data Encodings', icon: 'Binary' },
};